# conda env export --from-history | grep -v "^prefix: " > environment.yml
name: caa
channels:
  - pytorch
  - conda-forge
  - ankurankan
  - defaults
dependencies:
  - python=3.8
  - jupyterlab
  - matplotlib
  - numpy
  - tqdm
  - scikit-learn
  - ipython
  - scikit-image
  - ca-certificates
  - certifi
  - openssl
  - pgmpy
